server:
  port: 8080

logging:
   level:
        tk.mybatis: debug
        com.darklar7.mybatis.mapper: debug
        org.springframework:
              security: DEBUG
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true


mybatis:
    type-aliases-package: com.darklar7.mybatis.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.darklar7.mybatis.utils.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
